# Generated by Django 3.2.4 on 2021-12-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.IntegerField(unique=True)),
                ('voter_candidate', models.CharField(max_length=50)),
                ('voter_candidate_id', models.IntegerField()),
            ],
        ),
    ]
