#!/usr/bin/env bash
#!/bin/bash -f

TARGET=main
GCC=g++

COMMAND=${1:-'all'}

if [[ $COMMAND == 'all' ]]
then
    $GCC $TARGET.cpp -o $TARGET
    ./$TARGET
fi

if [[ $COMMAND == 'clean' ]]
then
    rm $TARGET
fi